services:
  reachy_2023:
    image: pollenrobotics/reachy_2023:1.1
    container_name: reachy_2023
    privileged: true
    environment:
      - ROS_DOMAIN_ID=$ROS_DOMAIN_ID
      - DISPLAY=$DISPLAY
      - "RCUTILS_CONSOLE_OUTPUT_FORMAT=[{severity}]: {message}"
      - $HOME/.ssh:/home/reachy/.ssh
    volumes:
      - $PWD:/opt/docker_reachy_2023_src:ro
    network_mode: "host"
    entrypoint:  /package/start.sh



